# Generated by Django 3.2.15 on 2022-09-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='new_place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imag', models.ImageField(upload_to='pic')),
                ('name', models.ImageField(max_length=250, upload_to='')),
                ('descript', models.TextField()),
            ],
        ),
    ]
