# Generated by Django 3.2.15 on 2022-09-15 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staticapp', '0003_auto_20220915_2025'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_profile',
        ),
    ]
